# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5ad818055edd449e80bb9da8d91813fcb5ed356acbe5182ca97f185cd129fe8215052f97cc4e16b5c1de456bba229a3f5eda7d6857617a7f42c8c4cae5daa26

test:
  secret_key_base: 2a2f46151f640044227d9292bd32c10cb64cccf0fd3a5b5a09d0c2b83323334a09ec3d30340b149a89d2c688b272cbd728b610589d117f5183884aa00a3492a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
