# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f43d8259a4e153c5bb96dd30e15f18bf8ba52f14e35de67326223aec8ad8db78736edca3374675477931aea2cbb135683507c3105c7d63cf61a0369ed1405905

test:
  secret_key_base: 2504bb07a4869b0c56338a68cb89a70d04722cfe477e57709453c6776ab33f43c829a96114a948de8612f4f7b8f4b8dc8318c5487abbbfc2f74ad85adfdf51be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
